### ISSUE TITLE
Initial do

### ISSUE THREAD

**Issue by achafetz** [achafetz/PartnerProgress#1]
new do files uploaded. test them out and see what you think. you'll need run the initialize do file first to setup the folder structure and then store the frozen file into the RawData folder. 

the output is a bit...raw. need to think about what to do to make it easier on the audience and to call out low performers.

**Comment by jaliasd** [comment]
I see your point. I have two tiny changes to the _reports do file to get it to run. For the output, I think we could either 1) set up some dashboards to run automatically or 2) re-jigger it  (possibly with putexcel) to make the output easier to use. My sense is that people will find it more intuitive if for each tab, IM for example, the unit of observation for that tab is IM.
