### ISSUE TITLE
genPPR creates a csv file name incompatible with template

### ISSUE THREAD

**Issue by jaliasd** [achafetz/PartnerProgress#25]
I ran genPPR and the .csv it created in RawData had the stub FY2018Q4

When you define the pd in the template, it calculates FY2019Q1 and then threw an error 

The `pd` section of the highlighted error

![image](https://user-images.githubusercontent.com/8836685/52470247-48530580-2b96-11e9-9f7b-d982df2d1e1f.png)

**Comment by achafetz** [comment]
I think this should be resolved via the user in the template. 

In the template in the rs tab, the user is suppose to specify the `data_qtr_date`, which is defined in the comment box as "be the first day of the quarter, 1/1/20XX, 4/1/20XX, 7/1/20XX, or 10/1/20XX". Updating this variable will then update the `pd` which is used in saving above.

![image](https://user-images.githubusercontent.com/8933069/52492698-9fba9b00-2bc1-11e9-8914-5f3eb82ba1ae.png)
